blank_issues_enabled: true
contact_links:
- name: 🙋🤔‍Question/Doubt
  url: https://www.youtube.com/c/DoKcommunity
  about: Feel free to ask any questions on our Slack channel.
- name: DOK Community support
   url: https://join.slack.com/t/dokcommunity/shared_invite/zt-10v7uncvp-jNFwulsVWvUO0SKMDTjwAw
   about: Feel free to get involved and clear your doubts here.